site_name: Pawa IT Cloud Mastery Training
site_author: Pawa IT Solutions
site_description: A comprehensive training guide for Cloud Mastery covering DevOps and Virtual Agents.
site_url: https://cloudmastery.cloudpartner.africa


theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - navigation.instant
    - navigation.tracking
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition  # This enables !!! note syntax
  - pymdownx.details  # This enables collapsible admonitions
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra_css:
  - assets/css/extra.css

nav:
  - Home: index.md
  - "Introduction":
      - "Cloud Mastery Training Introduction": introduction.md
  - "Automate Securely":
      - "DevOps & CI/CD on GCP Lab": devops/devops-lab.md
      - "Setup Cloud SQL": devops/setup-cloud-sql.md
      - "Setup GitHub": devops/setup-github.md
      - "CI/CD Pipeline Setup": devops/setup-backend-pipeline.md
      - "Trigger the Pipeline": devops/setup-frontend-pipeline.md
      - "Access the Application": devops/accessing-the-application.md
  - "Build Your Agent":
      - "Overview": virtual-agent/sokoai-lab.md
      - "Step 1: Initial Setup": virtual-agent/sokoai-setup.md
      - "Step 2: Building Playbooks": virtual-agent/sokoai-playbooks.md
      - "Step 3: Setting Up Tools": virtual-agent/sokoai-tools.md
      - "Step 4: Agent Instructions": virtual-agent/sokoai-agent-instructions.md
      - "Step 5: Deployment": virtual-agent/sokoai-deployment.md
      - "Step 6: Testing": virtual-agent/sokoai-testing.md
  - "End of Training":
      - "End of Training": end-of-training.md
extra:
  generator: false

plugins:
  - search
  - awesome-pages